// BUG-2919 behavior harness: executes the real long-press drag-select IIFE
// (generated by ReaderSelectionScripts.longPressDragGestureScript and written to
// a file by the Dart test) against a fake document and a virtual clock, then
// replays touch sequences and reports, per scenario, whether the long press
// claimed the touch and whether a swipe page turn would still fire.
//
// argv: <scriptPath> <swipeDistPx>
// stdout: one JSON object {scenarioName: {selected, pageTurn}}.
// Assertions live in the Dart test; this file only executes and reports.
'use strict';

const fs = require('fs');
const vm = require('vm');

const scriptPath = process.argv[2];
const swipeDist = Number(process.argv[3]);
if (!scriptPath || !(swipeDist > 0)) {
  console.error('usage: node <harness> <scriptPath> <swipeDistPx>');
  process.exit(2);
}
const source = fs.readFileSync(scriptPath, 'utf8');

const FRAME_MS = 16;

function run(steps) {
  let now = 0;
  let timers = [];
  let nextId = 1;
  const listeners = {};
  let began = 0;

  const fushiSelection = {
    getSelectableCharacterAtPoint: () => ({ ch: 'あ' }),
    beginRangeSelection: () => { began += 1; return true; },
    updateRangeSelection: () => {},
    endRangeSelection: () => {},
  };
  const window = { fushiSelection };
  const textNode = { closest: () => null };
  const document = {
    addEventListener: (type, fn) => { (listeners[type] = listeners[type] || []).push(fn); },
    elementFromPoint: () => textNode,
  };
  const sandbox = {
    window,
    document,
    setTimeout: (fn, ms) => { const id = nextId++; timers.push({ id, at: now + ms, fn }); return id; },
    clearTimeout: (id) => { timers = timers.filter((t) => t.id !== id); },
  };
  vm.runInNewContext(source, sandbox);

  function advance(ms) {
    const until = now + ms;
    for (;;) {
      timers.sort((a, b) => a.at - b.at);
      const due = timers[0];
      if (!due || due.at > until) break;
      timers.shift();
      now = due.at;
      due.fn();
    }
    now = until;
  }
  function fire(type, x, y) {
    const touch = { clientX: x, clientY: y };
    const ev = {
      target: textNode,
      cancelable: true,
      preventDefault: () => {},
      touches: type === 'touchend' ? [] : [touch],
      changedTouches: [touch],
    };
    (listeners[type] || []).forEach((fn) => fn(ev));
  }

  // Steps: {down:[x,y]} | {hold:ms} | {move:[dx,dy], ms} | {up:true}
  let x = 0, y = 0, startX = 0, startY = 0;
  let pageTurn = false;
  for (const s of steps) {
    if (s.down) {
      [x, y] = s.down; startX = x; startY = y;
      fire('touchstart', x, y);
    } else if (s.hold) {
      advance(s.hold);
    } else if (s.move) {
      const frames = Math.max(1, Math.round(s.ms / FRAME_MS));
      for (let i = 0; i < frames; i++) {
        advance(s.ms / frames);
        x += s.move[0] / frames;
        y += s.move[1] / frames;
        fire('touchmove', x, y);
      }
    } else if (s.up) {
      fire('touchend', x, y);
      // Mirrors _gestureEnd: a swipe turns the page on net displacement (no
      // time limit) unless the drag-select owns the touch.
      const net = Math.hypot(x - startX, y - startY);
      pageTurn = net >= swipeDist && !window.__fushiTextSelectDragActive;
    }
  }
  return { selected: began > 0, pageTurn };
}

const scenarios = {
  // A deliberate long press: finger stays put past the platform timeout.
  holdStill: [{ down: [100, 100] }, { hold: 500 }, { up: true }],
  // Natural page turn with a short rest before swiping (the user report).
  restThenSwipe: [
    { down: [300, 100] }, { hold: 350 }, { move: [-120, 0], ms: 150 }, { up: true },
  ],
  // Slow, deliberate swipe at 40px/s over one second.
  slowSwipe: [{ down: [300, 100] }, { move: [-40, 0], ms: 1000 }, { up: true }],
  // Quick tap.
  tap: [{ down: [100, 100] }, { hold: 120 }, { up: true }],
};

const out = {};
for (const name of Object.keys(scenarios)) out[name] = run(scenarios[name]);
console.log(JSON.stringify(out));
