// 生成排行榜「总字数 ≈ 读完 N 卷某作品」用的随包参考作品表。
//
//   dart tool/leaderboard/fetch_jiten_reference_works.dart
//
// 数据源：jiten.moe 公开 API（`GET https://api.jiten.moe/api/media-deck/get-media-decks
// ?offset=0&sortBy=popularity&mediaType=<t>`），按人气取每类前若干部的
// `characterCount`（全作字数）与 `childrenDeckCount`（卷 / 集数）。只在开发机上
// 手动跑一次，产物是 `lib/src/leaderboard/leaderboard_reference_works_data.dart`
// 的 const 表——**app 运行时不联网**。要刷新数据就重跑本脚本并提交产物。
import 'dart:convert';
import 'dart:io';

/// jiten mediaType → 产物里的种类名。
const Map<int, String> _kinds = <int, String>{
  1: 'anime',
  4: 'novel',
  7: 'visualNovel',
  9: 'manga',
};

/// 每类取前几部（按 jiten 人气）。
const int _perKind = 12;

/// 字数太少的条目（短片、单话）当参照物没意义。
const int _minUnitChars = 3000;

Future<List<Map<String, Object?>>> _fetch(HttpClient http, int type) async {
  final Uri uri = Uri.parse(
    'https://api.jiten.moe/api/media-deck/get-media-decks'
    '?offset=0&sortBy=popularity&mediaType=$type',
  );
  final HttpClientRequest req = await http.getUrl(uri);
  final HttpClientResponse res = await req.close();
  if (res.statusCode != 200) {
    throw HttpException('jiten $type → ${res.statusCode}', uri: uri);
  }
  final Object? body = jsonDecode(await res.transform(utf8.decoder).join());
  final List<Object?> data =
      (body! as Map<String, Object?>)['data']! as List<Object?>;
  return data.cast<Map<String, Object?>>();
}

/// 去掉副标题（`無職転生 ～異世界行ったら本気だす～` → `無職転生`）：文案里只放
/// 一眼认得出的主标题。只认全角 / 波浪类分隔，ASCII `-` 常是标题本体（9-nine-）。
String _shortTitle(String raw) {
  final String t = raw.trim();
  final String head = t.split(RegExp(r'\s*[～~－]')).first.trim();
  return head.isEmpty ? t : head;
}

String _dartString(String s) =>
    "'${s.replaceAll(r'\', r'\\').replaceAll("'", r"\'").replaceAll(r'$', r'\$')}'";

Future<void> main() async {
  final HttpClient http = HttpClient();
  final StringBuffer rows = StringBuffer();
  int count = 0;
  try {
    for (final MapEntry<int, String> kind in _kinds.entries) {
      int taken = 0;
      for (final Map<String, Object?> deck in await _fetch(http, kind.key)) {
        if (taken >= _perKind) break;
        final int chars = (deck['characterCount'] as num?)?.toInt() ?? 0;
        final int children = (deck['childrenDeckCount'] as num?)?.toInt() ?? 0;
        final String title = _shortTitle(
          deck['originalTitle'] as String? ?? '',
        );
        if (title.isEmpty || chars <= 0) continue;
        // 视觉小说按整部算（jiten 的子 deck 是章 / 篇，不是可单独买的卷）。
        final int parts = kind.value != 'visualNovel' && children > 0
            ? children
            : 1;
        final int unitChars = (chars / parts).round();
        if (unitChars < _minUnitChars) continue;
        rows.writeln(
          '  LeaderboardReferenceWork(jitenId: ${deck['deckId']}, '
          'kind: LeaderboardReferenceKind.${kind.value}, '
          'title: ${_dartString(title)}, '
          'totalChars: $chars, parts: $parts),',
        );
        taken++;
        count++;
      }
    }
  } finally {
    http.close();
  }
  final String today = DateTime.now().toUtc().toIso8601String().substring(
    0,
    10,
  );
  final File out = File(
    'lib/src/leaderboard/leaderboard_reference_works_data.dart',
  );
  out.writeAsStringSync('''
// GENERATED by tool/leaderboard/fetch_jiten_reference_works.dart — do not edit.
// 数据源：jiten.moe（https://jiten.moe）公开 API 按人气排序的前 $_perKind 部 / 类，
// 取于 $today。字段：全作字数 characterCount、卷 / 集数 childrenDeckCount。
// 运行时不联网；刷新 = 重跑生成脚本。

import 'package:fushi/src/leaderboard/leaderboard_reference_works.dart';

/// 随包参考作品表（$count 部）。
const List<LeaderboardReferenceWork> kLeaderboardReferenceWorks =
    <LeaderboardReferenceWork>[
$rows];
''');
  stdout.writeln('wrote $count works → ${out.path}');
}
